# Generated by Django 3.2 on 2024-11-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adopciones',
            fields=[
                ('id_adopcion', models.BigAutoField(primary_key=True, serialize=False)),
                ('condiciones_hogar', models.TextField(blank=True, null=True)),
                ('estado_solicitud', models.CharField(max_length=9)),
                ('experiencia_con_perros', models.TextField(blank=True, null=True)),
                ('fecha_solicitud', models.DateField(blank=True, null=True)),
                ('motivo_adopcion', models.TextField(blank=True, null=True)),
                ('otros_animales', models.TextField(blank=True, null=True)),
                ('responsable_financiero', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'adopciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Albergues',
            fields=[
                ('id_albergue', models.BigAutoField(primary_key=True, serialize=False)),
                ('correo', models.CharField(blank=True, max_length=255, null=True)),
                ('departamento', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('distrito', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'albergues',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id_mensaje', models.AutoField(primary_key=True, serialize=False)),
                ('emisor', models.CharField(blank=True, max_length=8, null=True)),
                ('fecha_envio', models.DateTimeField()),
                ('mensaje', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'chat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Donaciones',
            fields=[
                ('id_donacion', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('fecha_donacion', models.DateField(blank=True, null=True)),
                ('monto_total', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'donaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('correo', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_producto', models.CharField(blank=True, max_length=7, null=True)),
            ],
            options={
                'db_table': 'empresas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mascotas',
            fields=[
                ('id_perro', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('edad', models.IntegerField()),
                ('esterilizado', models.TextField()),
                ('imagen', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre', models.CharField(max_length=255)),
                ('raza', models.CharField(max_length=255)),
                ('sexo', models.CharField(max_length=6)),
                ('vacunas_completas', models.TextField()),
                ('tamano', models.CharField(max_length=7)),
            ],
            options={
                'db_table': 'mascotas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PreguntasFormulario',
            fields=[
                ('id_pregunta', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'preguntas_formulario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion_producto', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_producto', models.CharField(blank=True, max_length=100, null=True)),
                ('precio', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RespuestasFormulario',
            fields=[
                ('id_respuesta', models.AutoField(primary_key=True, serialize=False)),
                ('respuesta', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'respuestas_formulario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transacciones',
            fields=[
                ('id_transaccion', models.AutoField(primary_key=True, serialize=False)),
                ('estado_transaccion', models.CharField(blank=True, max_length=10, null=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transacciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('contrasena', models.CharField(blank=True, max_length=255, null=True)),
                ('correo', models.CharField(blank=True, max_length=255, null=True)),
                ('departamento', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('distrito', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_usuario', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
